version: "3.8"
services:
  web:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynet
    depends_on:
      - app

  app:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    links:
      - db
    networks:
      - mynet
    command: node index.js

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
    ports:
      - 5432:5432
    volumes:
      - ./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynet
networks:
  mynet:
