version: "3.8"
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "80:80"
    networks:
      - mynet-app

  app:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    # environment:
    #   - NODE_ENV=development
    links:
      - db
    networks:
      - mynet-app
      - mynet-db

  db:
    image: postgres:latest
    env_file:
      - ./backend/.env
    # environment:
    #   # - POSTGRES_DB=postgres
    #   # - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=mypassword
    ports:
      - "2345:5432"
    volumes:
      - ./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynet-db

networks:
  mynet-app:
  mynet-db:
