version: "3.8"
services:
  app:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    links:
      - db
    networks:
      - mynet
    command: node index.js
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= pass
      - POSTGRES_DB= db
    ports:
      - 5432:5432
    volumes:
      - ./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynet
networks:
  mynet:
