version: "3.8"
services:
  app:
    restart: always
    build: ./backend

    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    links:
      - db
    networks:
      - mynet
    command: node index.js

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
    ports:
      - 5432:5432
    volumes:
      - ./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynet
networks:
  mynet:
