name: Build and push image to Docker Hub
on:
  [workflow_dispatch]

jobs:
  push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t jijamesji/practice-repo:latest .
          docker push jijamesji/practice-repo:latest